### ISSUE TITLE
AttributeError: Document instance has no attribute 'file_basename'

### ISSUE THREAD

**Issue by jwilk** [jlsutherland/doc2text#2]
``` python
>>> import doc2text
>>> doc = doc2text.Document()
>>> doc.read('test.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jwilk/.local/lib/python2.7/site-packages/doc2text/__init__.py", line 67, in read
    self.file_basepath, self.file_basename + '_temp.png'
AttributeError: Document instance has no attribute 'file_basename'
```

Tested with git master (41dca91dda625b11633df77e45401787ea5a55a5).

**Comment by jlsutherland** [comment]
Awesome. Thanks for tracking this down. Will merge #3
