### ISSUE TITLE
ModuleNotFoundError: No module named 'PyPDF2'

### ISSUE THREAD

**Issue by alexauvray** [jlsutherland/doc2text#28]
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import doc2text
  File "/Users/Stan/Downloads/doc2text-master/doc2text/__init__.py", line 6, in <module>
    import PyPDF2 as pyPdf
ModuleNotFoundError: No module named 'PyPDF2'
```

**Comment by janjaromirhorak** [comment]
I have the same error. I have PyPDF2 installed (it shows up in `/usr/lib/python3/dist-packages/PyPDF2/` as all the other packages), but when I try to `import PyPDF2` i get the following error:
```>>> import PyPDF2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyPDF2'```

I am running Ubuntu 17.10 and I have PyPDF2 installed using the package manager (`apt install python3-pypdf2`).

Any Ideas how to work around this issue?

**Comment by KugelschreiberY** [comment]
Having the same issue here, any updates?
